pub(crate) const WS_CONFIG_ENV_VAR: &str = "WS_CONFIG_PATH";
pub(crate) const SERVER_SOCKET_PATH_ENV_VAR: &str = "SERVER_SOCKET_PATH";
pub(crate) const MONITOR_EXECUTABLE_ENV_VAR: &str = "MONITOR_EXECUTABLE_PATH";
