[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
clap_derive = "4.5.32"
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }

daemon-interface = { path = "../../lib/daemon-interface" }
